apiVersion: v1
kind: ConfigMap
metadata:
  name: root-ssh-pubkeys
  namespace: kube-system
data:
  mykey1: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCyylYgCothbAElj8qBFTEnzw0d2oTeRkMZd6yXC8+HXa8CVd8q90DDrtae/hy1ISnwhWPRJ/YiLecKLOLAgypdb0tKYQ2D88wbUy1xoim1K/QSIjuqi2TqAHv1cvuYJLczcOkOEhkg7NPDErZFArqK62Enn0x4fjSlH5ofcl5GKLAz9hY3am1v/rup1pxr6NZi2tDctWf8GLH4WgU2/NDRh02NEyzcRx5ioypRtzX6T6nb0Q/TmG+tsgXZYstYP41SKxJkXP6MxA/+dunW1xM7K14dMz4BPEbMSukMBeTZV3ciEoZOghgKR02qu3KbEYFnTIJ7zYEfwOwfLfnLWtRa8Syy6U2i3KsOa+I+fzV88/6Gg75Vk4NtiZ8LnTSgDVcW/+C7K70bEaF2LBMkRyrHxdJ6v9DHtq8GEDAAqFZ6I2y/3K1TGRPsw0zhWXJc/SZc2sg+wcc3xHVlYfGeBUHE3QNWXiqs0yvyYQ6PsKduGdlrC4ZSeml7r1zHg2G8oc6x8Oyhm4hxpixaFEcD9ye5RdR1u8VAusPM/HAnOoLehf1yq1npuUyxN055yK4UFQc6N2y6aoqpyyiosSSxrXOtqgD9cw75YVv/EMPdcMFzxEN2MSYKp1e/aH8JXVbpPE4eRjIn1JRkz2OJXWYls5htBUXagP2BEPzeO+P5oCaFUw== root access to LKE nodes"
